apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-readiness
  name: pod-readiness
spec:
  containers:
  - args:
    - sh
    - -c
    - touch /tmp/ready && sleep 1d
    image: busybox:1.31.0
    name: pod-readiness
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 0.2
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - cat /tmp/ready
      initialDelaySeconds: 10
      periodSeconds: 10
  restartPolicy: Always
status: {}
