apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesbooklb
  labels:
    app: salesbooklb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8slab01.azurecr.io/nginx-sample:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesbookapache
  labels:
    app: salesbookapache
spec:
  replicas: 10
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: k8slab01.azurecr.io/apache-docker:latest
        ports:
        - containerPort: 81
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: mf-nginx
  labels:
    run: mf-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: mf-nginx-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: mf-apache-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: apache