
apiVersion: apps/v1
kind: Deployment
metadata:
  name: versions-app1
spec:
  selector:
    matchLabels:
      app: versions-app
      ver: v1
  replicas: 5
  template:
    metadata:
      labels:
        app: versions-app
        ver: v1
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-meta-version": "1"
        "consul.hashicorp.com/service-tags": "v1"
    spec:
      containers:
      - name: application
        image: cloudstateu/versions-app:1
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: versions-app2
spec:
  selector:
    matchLabels:
      app: versions-app
      ver: v2
  replicas: 5
  template:
    metadata:
      labels:
        app: versions-app
        ver: v2
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-meta-version": "2"
        "consul.hashicorp.com/service-tags": "v2"
    spec:
      containers:
      - name: application
        image: cloudstateu/versions-app:2
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
