apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: applicationlogger
spec:
  replicas: 2
  selector:
    matchLabels:
      id: cleaner
  template:
    metadata:
      labels:
        id: cleaner
    spec:
      volumes:
      - name: logs
        emptyDir: {}
      initContainers:
      - name: init
        image: bash:5.0.11
        command: ['bash', '-c', 'echo init > /var/log/applicationlogs/cleaner.log']
        volumeMounts:
        - name: logs
          mountPath: /var/log/applicationlogs
      containers:
      - name: application-container
        image: bash:5.0.11
        args: ['bash', '-c', 'while true; do echo `date`: "Another line in the log" >> /var/log/applicationlogs/cleaner.log; sleep 1; done']
        volumeMounts:
        - name: logs
          mountPath: /var/log/applicationlogs
      - name: logger
        image: busybox:1.31.0
        command: ["sh", "-c", "tail -f /var/log/applicationlogs/cleaner.log"]
        volumeMounts:
        - name: logs
          mountPath: /var/log/applicationlogs   